"use client";
import Link from "next/link";
import {
	Admin,
	Resource,
	Datagrid,
	List,
	TextField,
	BooleanInput,
	Edit,
	SimpleForm,
	TextInput,
	Menu,
	MenuItemLink,
	useResourceDefinitions,
	Create,
	required,
	Layout,
} from "react-admin";
import { RichTextInput } from "ra-input-rich-text";
import customDataProvider from "@/react-admin/customDataProvider";
import { useAuthContext } from "@/context/authContext";
import { useCallback } from "react";

export default function ReactAdmin() {
	return (
		<Admin dataProvider={customDataProvider} layout={CustomLayout}>
			<Resource
				name="jobs"
				list={JobsList}
				edit={JobsEdit}
				create={JobsCreate}
			/>
			{/* <Resource name="materials" list={MaterialList} edit={MaterialEdit} create={MaterialCreate} /> */}
		</Admin>
	);
}

const CustomLayout = (props: any) => <Layout {...props} menu={CustomMenu} />;

export const CustomMenu = (props: any) => {
	const resources = useResourceDefinitions();

	return (
		<Menu {...props}>
			{/* Standard resource links (optional, you can just list your resources here) */}
			{/* Your custom link to /profile */}
			<Link
				className="text-orange-500 px-4 py-[6px] underline mt-6"
				href="/profile">
				Profile
			</Link>
			{resources.jobs && <MenuItemLink to="/jobs" primaryText="Jobs" />}
			{/* {resources.materials && (
				<MenuItemLink to="/materials" primaryText="Materials" />
			)} */}

			{/* Add more custom links or standard resources here */}
			{/* <MenuItemLink to="/custom-page" primaryText="Custom Page" leftIcon={<SomeOtherIcon />} /> */}
		</Menu>
	);
};

export const JobsList = () => (
	<List>
		<Datagrid>
			<TextField source="en_title" />
			<TextField source="sp_title" />
			<TextField source="image_url" />
		</Datagrid>
	</List>
);

export const JobsEdit = () => (
	<Edit>
		<SimpleForm>
			<TextInput source="en_title" />
			<TextInput source="sp_title" />
			<RichTextInput source="en_description" />
			<RichTextInput source="sp_description" />
			<BooleanInput source="is_active" />
			<BooleanInput source="is_fulltime" />
			<BooleanInput source="is_temporary" />
		</SimpleForm>
	</Edit>
);

export const JobsCreate = () => {
	const { user } = useAuthContext();

  console.log(user)

	// 2. Wrap the transform function in useCallback
	// This tells React to create a new version of this function ONLY when the `user` object changes.
	const transform = useCallback(
		(data: any) => ({
			...data,
			by_user_id: user ? user.id : null // Now this will always have the latest user.id
		}),
		[user]
	); // The dependency array ensures it updates when `user` does

	return (
		<Create transform={transform}>
			<SimpleForm>
				{/* id is usually auto-generated by the backend, so don't include it in Create form */}
				<TextInput source="en_title" validate={required()} />
				<TextInput source="sp_title" validate={required()} />
				<RichTextInput source="en_description" />
				<RichTextInput source="sp_description" />
				<BooleanInput source="is_active" />
				<BooleanInput source="is_fulltime" />
				<BooleanInput source="is_temporary" />
			</SimpleForm>
		</Create>
	);
};
